### PR TITLE
Python3-Support Part1

### PR DESCRIPTION
**Pull request by SecureAB**
This doesn't add full python3, it even doesn't allow zbid to work in python3. But it contains first steps towards the Python3 support. It it still compatible to Python2.7 .The following was made:
- Python3 Support for zigbee_crypt. This allow `pip3 install .` to work.
- Use relative paths for imports
- Remove unused imports where 
- Update the print statements to the print function. Imports also `print_function` from `__future__` where needed.
- Fix indentation

The performance differences between `range` and `xrange` in this code should be negligible, so I use `range` everywhere. The same is true for `dict.items()`.

If you want to keep a clean history, you can simply squash the commits. I decided to split it up in multiple parts, so the diffs of the separate parts are smaller.

### CODE REVIEW

**Comment by SecureAB** [comment]
The performance differences between `range` and `xrange` in this code should be negligible, so I use `range` everywhere. The same is true for `dict.items()`.

**Comment by SecureAB** [comment]
I just rebased the commits to resolve the merge conflict.

**Comment by rmspeers** [comment]
@SecureAB please see the py3 branch that was based off of your branch originally, but has diverged a bit it appears. Do you mind seeing if py3 branch works for you?

**Comment by SecureAB** [comment]
@rmspeers Sorry, I had only temporary access to the required ZigBee-USB Dongles and other ZigBee hardware until April. So I can't test it anymore.

**Comment by rmspeers** [comment]
No problem, thanks for getting it all going! @taylorcenters will finish testing/analysis and close once validated.

**Comment by taylorcenters** [comment]
Python 3 support has been merged - thanks for all your help!

**Pull request closed without merging**
