### PR TITLE
Add support for custom TI CC2531 firmware that provides sniffing/injection capabilities

### PR DESCRIPTION
**Pull request by virtualabs**
Hi,

I created a specific driver for a custom firmware compatible with CC2531 that implements packet sniffing and injection (more info here: https://github.com/virtualabs/cc2531-killerbee-fw). I've been testing it during the last few days, and it seems stable. 

I think I modified the correct files to add automatic support for this firmware (however, it still needs to be enabled in config.py). 
I didn't modify the README files to mention this custom firmware and how to set it up, but it can definitely be added if required. 

Hope you'll find it useful ;)

### CODE REVIEW

**Comment by virtualabs** [comment]
I found a bug yesterday in my CC2531 firmware, now fixed in the last release. I don't know if you gave it a try, but if you did you should try it again with the latest firmware version (works far better as the previous one strips every last two bytes of sniffed packets ...).

**Comment by rmspeers** [comment]
From my first look - am I mistaken that this used to be, on the default sniffing firmware, a USB device accessed directly as such, and now it is an USB ACM device accessed over USB serial? Is there a way to avoid USB serial, which would allow easier identification without the issues we see with blind enumeration of serial devices to determine the type?

**Comment by virtualabs** [comment]
I just thought Killerbee still relies on USB serial devices (required by ApiMote and other devices) so it would be ok ;). 
I'm not very proud of it indeed, but this first version relies on Contiki's default serial interface for CC2531 as I tried to get a working sniffer/injector without digging too much into Contiki. And you're right, TI CC2531 is able to expose some USB endpoints that could be used to identify the device and make killerbee detect it easily, as the default sniffing firmware does. Well, I can have a look at what it would take to move from USB serial to a full USB device.

**Comment by rmspeers** [comment]
Yes, fully agreed that some device support uses USB serial - and we can do the same for this device for sure, if there's not an easy path to a 'native USB' option. I only mentioned as all of those discovery routines are hacky and cause issues, so I was thinking that as this device's default firmware and chipset supported USB endpoint comms (vs the others that are via an FTDI), it may be nice to keep that.

With the `/dev/ttyACM0` serial endpoint, I'm having issues on an Ubuntu 18.04 native machine talking to it - when I look a bit, I see that when I send the 3 bytes used in the discovery routine, I don't get any data sent back from the endpoint.

**Comment by virtualabs** [comment]
Got your point, and yes the tiny serial protocol I implemented can be messed up if you have other serial devices enabled in your config.py file. And this is why using a serial interface is no good I guess. USB communications with the CC2531 is kind of new to me, but I managed to wrap the serial protocol in somekind of bulk data transfer so it won't be long to get the driver talk to the dongle through USB communication. I'm pretty sure there's a better way to do it, but I'm no USB expert.

**Comment by virtualabs** [comment]
Allright, USB communication is now implemented. CC2531 dongle uses USB bulk transfers to communicate with host, and it looks pretty reliable (works OK on my machine). I've put the corresponding firmware here if you want to give it a try, as it surely needs more testing. 

[cc2531-bumblebee-v2.0.zip](https://github.com/riverloopsec/killerbee/files/5708016/cc2531-bumblebee-v2.0.zip)

**Comment by VortexGif** [comment]
I'm trying to get a CC2531 working with killerbee but zbid isn't showing the device. Tried a few different pieces of firmware but nothing. Just flashed the bumblebee v2 as well and windows is having an issue with the driver I think?

Do you know where I am going wrong , any help would be appreciated.

**Comment by rmspeers** [comment]
@virtualabs thanks, I'll give that a try as soon as I can and let you know!

**Comment by MartinoTommasini** [comment]
Hi, I was also working on the same capabilities a couple of months ago. I didn't write the cc2531 firmware from scratch but just extended the ZBOSS packet sniffer to add injection features and support to KillerBee. In case you want to take a look it's here: https://github.com/MartinoTommasini/ZBOSS_extended. I've tested it over 1/2 months and it was working for me.

I don't know whether it can still be of any help, given the great work of @virtualabs. 
Tell me if it makes sense to create a new pull request or not.

**Comment by wang70880** [comment]
> I'm trying to get a CC2531 working with killerbee but zbid isn't showing the device. Tried a few different pieces of firmware but nothing. Just flashed the bumblebee v2 as well and windows is having an issue with the driver I think?
> 
> Do you know where I am going wrong , any help would be appreciated.

I don't think this pull request implemented CC2531 support for zhid, just check the code in kbutils.devlist().

**Comment by virtualabs** [comment]
> > I'm trying to get a CC2531 working with killerbee but zbid isn't showing the device. Tried a few different pieces of firmware but nothing. Just flashed the bumblebee v2 as well and windows is having an issue with the driver I think?
> > Do you know where I am going wrong , any help would be appreciated.
> 
> I don't think this pull request implemented CC2531 support for zhid, just check the code in kbutils.devlist().

Code in kbutils.devlist() relies on `usbVendorList` and `usbProductList` (lines 41 and 42 of kbutils.py) to detect USB devices, and this PR adds Bumblebee vendor ID and product ID to these lists. zbid relies on kbutils.devlist() to enumerate devices, so it should detect a CC2531 running Bumblebee.

I think the problem comes from Windows, as it is not currently supported by Killerbee (see *Requirements* section in README.md that states: "KillerBee is developed and tested on Linux systems.").

**Comment by wang70880** [comment]
@virtualabs First thanks for your contribution to design the testbed for CC2531. Recently I am testing your impl.

For zbid and zbdump, they worked well.

For zbreplay, I used a previously dumped pcap file, which includes a single beacon request command.  From the KillerBee's output, it seems normal. 
```
Warning: You are using pyUSB 1.x, support is in beta.
zbreplay: retransmitting frames from './test.pcap' on interface 'CC2531 USB Dongle' with a delay of 1.0 seconds.
True
1 packets transmitted
```
But when I use Wireshark and another CC2531 adapter with stock firmware to observe the spoofed packet, I cannot see the it. Any idea to help me to debug?

**Comment by wang70880** [comment]
I

> @virtualabs First thanks for your contribution to design the testbed for CC2531. Recently I am testing your impl.
> 
> * For zbid, they worked well.
> * For zbdump, I select Beacon Request packets as testing packages. First I use CC2531 with stock firmware to sniff Beacon Request packets from Philips Hue Bulb, and found that the size of the packets is 70 bytes.
> 
> image
> Then I use zbdump with your firmware + KillerBee to dump a Beacon Request packets, only to find out that the size of dumped packet is 10 bytes.
> image
> 
> * For zbreplay, I used a previously dumped pcap file, which includes a single Beacon Request command.  From the KillerBee's output, it seems normal.
> 
> ```
> Warning: You are using pyUSB 1.x, support is in beta.
> zbreplay: retransmitting frames from './test.pcap' on interface 'CC2531 USB Dongle' with a delay of 1.0 seconds.
> True
> 1 packets transmitted
> ```
> 
> But when I use Wireshark and another CC2531 adapter with stock firmware to observe the spoofed packet, I cannot see the it.
> 
> Any idea to help me to debug the problem when using zbdump and zbreplay?

It seems like that KillerBee.inject() function sends a packet without FCS part. However, When I use Wireshark + cc2531 to sniff the packet, Wireshark can only accept packets with valid FCS. Here question comes: Since we cannot sniff and view the sent packet, how can we do the verification?

**Comment by VortexGif** [comment]
Hi , I am still having issues using bumble bee on the CC2531 stick. I have flashed it with bumblebee V2 and zbid is still not showing anything. When flashed with the orginal firmware from TI zbid shows the device , however when it is flashed with bumblebee nothing is showing within zbid.

lsusb shows the device , so I am not sure exactly what the issue is. Any help would be appreciated.

**Comment by virtualabs** [comment]
Just to be sure, you are using the py3 branch of killerbee, right ?

**Comment by VortexGif** [comment]
oh that must be the issue , please could you point me in the direction of how to use the py3 version?

**Comment by VortexGif** [comment]
I fixed my last issue , and figured out how to get the right branch installed on my machine. Killer bee 
 is now seeing the device , but when i try to run any tool I am getting an error. I'm not too sure what it is or how to fix it.
Screenshot from 2021-03-24 12-34-54

**Comment by virtualabs** [comment]
You are using python version 2.7 instead of python 3.x (see `killerbee-3.0.0b0-py2.7-linux-x86_64.egg` in your terminal output), that's why. Completely uninstall killerbee (py2 and py3), and then install it with the python3 interpreter and everything will work as expected.

**Comment by haxorthematrix** [comment]
I've been playing with this branch and the Bumblebee 2.0 firmware.  Things seem pretty stable for capture and transmit with PCAPs, however capturing to Daintree SNA fails:

```
sudo zbdump -i 3:15 -f 11 -W testreplaycap.dcf
/home/sec617/.local/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py:11: MatplotlibDeprecationWarning: 
The support for Qt4  was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  from matplotlib.backends.qt_compat import QtGui
Warning: You are using pyUSB 1.x, support is in beta.
zbdump: listening on 'CC2531 USB Dongle', channel 11, page 0 (2405.0 MHz), link-type DLT_IEEE802_15_4, capture size 127 bytes
Traceback (most recent call last):
  File "/usr/local/bin/zbdump", line 4, in <module>
    __import__('pkg_resources').run_script('killerbee==3.0.0b0', 'zbdump')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/killerbee-3.0.0b0-py3.6-linux-x86_64.egg/EGG-INFO/scripts/zbdump", line 106, in <module>
    dt.pwrite(packet['bytes'])
  File "/usr/local/lib/python3.6/dist-packages/killerbee-3.0.0b0-py3.6-linux-x86_64.egg/killerbee/daintree.py", line 50, in pwrite
    "0 1 32767\r\n"])                   # Unknown
TypeError: sequence item 6: expected str instance, bytes found
```

Also, subsequent attempts of conversion with zbconvert also fails:

```
sudo zbconvert -i testreplaycap.dump -o t.dcf
Traceback (most recent call last):
  File "/usr/local/bin/zbconvert", line 4, in <module>
    __import__('pkg_resources').run_script('killerbee==3.0.0b0', 'zbconvert')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/killerbee-3.0.0b0-py3.6-linux-x86_64.egg/EGG-INFO/scripts/zbconvert", line 55, in <module>
    outcap.pcap_dump(packet[1])
  File "/usr/local/lib/python3.6/dist-packages/killerbee-3.0.0b0-py3.6-linux-x86_64.egg/killerbee/daintree.py", line 26, in pcap_dump
    self.pwrite(packet)
  File "/usr/local/lib/python3.6/dist-packages/killerbee-3.0.0b0-py3.6-linux-x86_64.egg/killerbee/daintree.py", line 50, in pwrite
    "0 1 32767\r\n"])                   # Unknown
TypeError: sequence item 6: expected str instance, bytes found

```

**Comment by rmspeers** [comment]
>  Things seem pretty stable for capture and transmit with PCAPs, however capturing to Daintree SNA fails

Thanks @haxorthematrix  - I'm tagging in @taylorcenters  as I think that he was deprecating the Daintree format in this py3 branch as he didn't know of people using it. Is that the case @taylorcenters ? If so, was it perhaps not fully deprecated or left in an odd state and we can clean that up - unless @haxorthematrix  you think there is a need for it still?

**Comment by haxorthematrix** [comment]
I use the Daintree format all of the time, especially because it is super easy to isolate a single packet for replay and such with the uber l33t haxor tool, vi.

**Pull request merged**
