### PR TITLE
Change datetime import and method to fix AttributeError in zbfind

### PR DESCRIPTION
**Pull request by jbisterfeldt**
Ran into the following error when running zbfind with rzusb passive (not flashed with killerbee firmware):

File "/usr/local/lib/python2.7/dist-packages/killerbee-2.6.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/zbfind", line 1039 in run AttributeError: type object 'datetime.datetime' has no attribute 'datetime'

I can find no logical reason this issue arose, but changing the import and methods in zbfind has resolved it for me on Kali 4.16.16-2kali2 (2018-07-04), Python 2.7.15. Tested on two machines with the same OS patch level.

### CODE REVIEW

**Comment by jbisterfeldt** [comment]
Some additional testing is pointing to Kali as the source - closing this PR.

**Comment by rmspeers** [comment]
Thanks for the report. Odd indeed. Let me know if you see it again.

**Comment by regalhotpocket** [comment]
@rmspeers I got the same issue, and I fixed it in a similar way. Same setup with unflashed, passive, rbfind, but I was on Ubuntu 18.04.

**Comment by rmspeers** [comment]
Thanks for the feedback. I looked at this again and I still think that the calls are equivalent -- so Python 2.7 should be acting the same in each case. In fairness, I am testing on macOS.

```
$ python
Python 2.7.10 (default, Oct  6 2017, 22:29:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.datetime.now()
datetime.datetime(2018, 8, 26, 19, 28, 8, 611734)
>>> ^D
$ python
Python 2.7.10 (default, Oct  6 2017, 22:29:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from datetime import datetime
>>> datetime.now()
datetime.datetime(2018, 8, 26, 19, 28, 26, 388793)
```

If this PR is indeed what is helping, then I will test on Ubuntu and Python 3 and we can merge.

**Pull request closed without merging**
