### PR TITLE
Python3 support, Sewio updates

### PR DESCRIPTION
**Pull request by whoot**
Phew.. I merged the dev and some stuff of the Python3 branch, updated everything else to Python3 and added the Sewio stuff to it.
Also did some bugfixing.

Needs to be tested thoroughly! Just tested some basic stuff with the Sewio, but nothing else of the 'killerbee/dev_*' stuff.

Works/Tested:

- scripts/configure_sewio.py
- zbid
- zbreplay
- zbassocflood
- zbjammer
- zbscapy
- zbstumbler
- zbdump
- zbwireshark

-zbwardrive
 -> basic functionality (without database or gps)
 -> this code is a mess and you should really clean it up
 -> doesnt stop the sniffer correctly

- zbdsniff
-> Transformed 'zigbee_crypt.c' correctly to python3, but got the following error message:
ERROR: Input file "../sample/control4-sample.pcap" is not able to be loaded. Is it a PCAP file? Daintree support was removed in KillerBee 2.7.1

=> dsnafile support has been removed, so i removed it in the tools, too.

### CODE REVIEW

**Comment by rmspeers** [comment]
See https://github.com/riverloopsec/killerbee/pull/204 which _should_ include the needed changes.

@taylorcenters  please make sure this branch doesn't have anything that we also want in the py3 branch.

**Comment by whoot** [comment]
@taylorcenters Please let me know when you are finished with the review so I can close this pull request and delete this branch finally :)

**Comment by taylorcenters** [comment]
I believe all updates addressed by this PR have been merged in. Thank you so much for this contribution.

**Comment by whoot** [comment]
Thanks for the update!

**Pull request closed without merging**
