### PR TITLE
Fix 64-byte truncation of Air Capture Packets.

### PR DESCRIPTION
**Pull request by Scytmo**
In Air Capture mode, the RZ USB Stick firmware sends 64 byte packets,
with longer captured 802.15.4 packets being sent over several USB
packets.  The python RZ USB Stick driver was not re-combining these
fragmented packets, instead simply returning the first 64-byte fragment,
and discarding the subsequent fragments, resulting in a short 802.15.4
captured frame (with corresponding bad FCS) being provided to the
killerbee utilities.

This fix re-combines fragmented 802.15.4 captured packets in the python
RZ USB Stick driver, resulting in the full 802.15.4 frames being provided to
the killerbee utilities.

### CODE REVIEW

**Comment by Scytmo** [comment]
This fixes issue #87

**Comment by riverloopsec** [comment]
Thanks. This looks good and I will review once more and approve when back
at a computer.

Thanks for making a fix!

**Comment by Scytmo** [comment]
I had to change the indentation level for some code, which makes git show the change
as being more extensive than it is.  When you're reviewing it, it's worth using something
like 'git diff -b' to ignore changes in whitespace so you can see more clearly what I've done.

**Comment by Acesonnall** [comment]
Nice job for implementing a potential fix. I'll give this a shot on my end.

**Comment by rmspeers** [comment]
@Acesonnall  - Did it work for you?

**Comment by rmspeers** [comment]
It looks like you're setting a new thing in the result, lqi. That is fine as it looks like you are still setting rssi/dbm/2, but just wanted to check.

**Comment by Scytmo** [comment]
Yes, the Air Capture for the RZ USB Stick puts the Link Quality Indicator at the end of the captured data.  You can see this in the firmware here:

https://github.com/riverloopsec/killerbee/blob/master/firmware/src/kb-rzusbstick/application/rzusbstick/air_capture.c#L613

Before my change, this byte was being thrown away as junk, here:
https://github.com/riverloopsec/killerbee/blob/master/killerbee/dev_rzusbstick.py#L474

Otherwise I didn't change anything regarding the other fields that are extracted from the air capture packets and returned by the driver in the dict.

**Comment by riverloopsec** [comment]
Yes, looked like that - just wanted to confirm. Thanks for adding.

**Comment by Acesonnall** [comment]
This fix worked for me. Zbwireshark still has the same issue. I was going to see if I could work on a fix (though my experience with programming for this is limited).

**Comment by Scytmo** [comment]
@Acesonnall 
> Zbwireshark still has the same issue

You mean the issue reported by @robertfullagar in #86 of zbdump/zbwireshark stalling when capturing packets?  Yes, as far as I can tell, that's entirely unrelated to this truncation issue.

And yes, I still see packet capture stalling with my RZ USB Stick, as reported originally in #86.  That's why I created the separate issue #87 for the unrelated truncation issue, because solving the truncation wasn't going to solve the stalling.  (I see that @rmspeers marked #86 as a duplicate (presumably of #87?), which I don't think is the case).

**Pull request merged**
