### PR TITLE
Handle overflow of RSSI for cc25xx

### PR DESCRIPTION
**Pull request by jbisterfeldt**
Encountered occasional overflow with clone cc25xx, leading to errors. This patch ensures the value doesn't overflow, and continues. Considered setting value to 0, but 255 is likely closer to "real" RSSI.

### CODE REVIEW

**Comment by rmspeers** [comment]
Thanks for the submission. Do you see this happening when there is very low RSSI and thus it underflows to loop back to be above 255, or what case triggers this?

I would expect with the following as pseudocode:

```
# parse byte as signed char; MAX value should be 127, MIN value -128, right?
                rssi = struct.unpack("b", framedata[-2])[0]  
# now range, as python is treating as an int and we aren't masking, should be from -201 to 54
                rssi  -= 73
# I'm missing something then on how RSSI can get over 255?
                # Dirty hack to compensate for possible RSSI overflow
                if rssi > 255:
                    rssi = 255 # assumed to be max, could also report error/0
```

Could you print out framedata as hex bytes when you get this to occur?

**Comment by jbisterfeldt** [comment]
I'll do some current diligence on this, and I agree with your pseudocode approach. I'll rework the commit when I have conditions and the time to do so. This patch allowed continual sniffing on 12+ CC2531 for > 24 hours, and is a bit naive. Thanks for the feedback!

**Comment by rmspeers** [comment]
Sounds good, let me know. I do like hearing that it is able to get continuous sniffing in a situation where it wasn't before! Just want to track down the root cause as I wonder if it may need a fix in a slightly different area of code.

**Comment by jbisterfeldt** [comment]
From what I hotfix-patched, it seems to be in the RSSI correction, and if I recall correctly, it was strictly overflow. Ensuring a valid one-byte value is returned solved the issue, but I'll do some testing to confirm the conditions.

**Review by taylorcenters — APPROVED** [review]

**Pull request merged**
